### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource through DRF-Spectacular

### ISSUE THREAD

**Issue by lev-slinsen** [cookiecutter/cookiecutter-django#3965] opened 2022-11-24 19:44 UTC
## What happened?
Making requests through DRF-Spectacular UI returns `TypeError: NetworkError when attempting to fetch resource.` instead of proper response.

## What should've happened instead?
Proper response.

## Additional details
Making a plain request without DRF-Spectacular returns proper response.

**Comment by lev-slinsen** [comment] 2022-11-24 19:53
Have replaced it with `drf-yasg`, it works fine. It looks like it's either a bug within spectacular itself or the way it's set up in cookiecutter django.

**Comment by browniebroke** [comment] 2022-11-24 23:08
Is that on local dev or prod?

**Comment by lev-slinsen** [comment] 2022-11-25 16:08
> 

On local, haven't tested on dev or prod.

**Comment by browniebroke** [comment] 2022-12-06 19:18
Right, I can reproduce. I think that's a duplicate of #3593. Your error is showing in the UI, but there are more details in the JS console.

**Closed by browniebroke** 2022-12-06 19:18 UTC
Labels: bug
