### ISSUE TITLE
domain.com redirected you too many times

### ISSUE THREAD

**Issue by AustinGilkison** [cookiecutter/cookiecutter-django#3090] opened 2021-03-10 21:34 UTC
## What happened?
I have recently set up a Django project and am trying to deploy it to production but getting a:
> Page isn't working domain.com redirected you too many times

## What should've happened instead?
The page should load as it normally did in local.

* Host system configuration: 
    * OS:
        * Amazon Linux 2

**Comment by Afrowave** [comment] 2021-03-10 21:36
Hi @AustinGilkison,

Did you assign the domain name when you were setting up the project?

**Comment by Andrew-Chen-Wang** [comment] 2021-03-19 20:56
@AustinGilkison Did you wait to get a certificate for users to be able to connect to https in the first place? There's a possibility the certification failed.

**Comment by AustinGilkison** [comment] 2021-03-20 00:05
Yes, The site is using a valid SSL. Once I removed the following from line 48 in compose/production/traefik/traefik.yml everything worked fine.
```
redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
```

**Comment by Andrew-Chen-Wang** [comment] 2021-03-20 01:15
Hm it could be because the Django settings is interfering with traefik? Try going to the http version instead of the https version WITHOUT line 48. Does it redirect? If not, then that's the point of Line 48. If it DOES redirect, then the Django settings may be interfering with the redirect somehow.

Also, you deployed to an EC2 instance but did you put a load balancer from AWS in front of your EC2?

**Comment by jcovington16** [comment] 2021-03-23 02:54
It seems like you are in an infinite loop when trying to redirect. Do you have django.contribs plugins/imports installed? i.e(djagno.contrib.sites, django.contrib.redirects) Have you checked the logs from the web server? I would also ask did you migrate your changes because this will create a django redirect table in your database.

**Comment by browniebroke** [comment] 2021-12-24 19:54
I cannot reproduce from a vanilla project. As other suggested, there might be something else misconfigured outside of the project.

I'm going to close this. You might have more luck on Stackoverflow.

**Closed** 2021-12-24 19:55 UTC
Labels: bug

**Comment by cjauvin** [comment] 2022-01-01 19:17
I am a new django-cookiecutter user so take what I say with a grain of salt, but I was struggling with a similar "too many redirects" issue, and in my case, when I switched my Cloudflare DNS records from "proxied" to "non-proxied", it made it work.

**Comment by tkin91e55** [comment] 2024-11-06 05:39
@cjauvin Saved me a day, I first turned off the redirect in Traefik. But considering complexity, prefer to turn off Cloudflare proxied record.
@browniebroke when I changed on my /etc/hosts, could not reproduce the same problem. I believe this is from "the outside" as you said, Cloudflare proxied record
