### ISSUE TITLE
whitenoise.runserver_nostatic is ignored

### ISSUE THREAD

**Issue by engAmirEng** [cookiecutter/cookiecutter-django#4469] opened 2023-07-18 13:00 UTC
## What happened?
whitenoise.runserver_nostatic has no effect because of the order of INSTALLED_APPS, so the runserver command of staticfiles app is used instead of whitenoise.runserver_nostatic app

**Comment by browniebroke** [comment] 2023-07-26 22:16
So... what? How does it impact you? Why is it a bug? Please provide more details about what's expected and what actually happened.

**Comment by engAmirEng** [comment] 2023-07-27 10:16
@browniebroke There is a package installed and added to project as Middleware and installed app but as it is now it has no use case, Django staticfiles run server is picked up instead of whitenoise's, how is this not a bug?

**Comment by browniebroke** [comment] 2023-07-27 10:42
> how is this not a bug?

I never said it wasn't: I ask for more details as I found your original message was a bit vague.

**Comment by browniebroke** [comment] 2023-07-27 10:51
For context, this was added in https://github.com/cookiecutter/cookiecutter-django/pull/2304

I can't remeber how to identify which command is used. From what I can see [in the Whitenoise docs](https://whitenoise.readthedocs.io/en/latest/django.html#using-whitenoise-in-development), we seem to be doing what's needed, as the app is isntalled before `django.contrib.staticfiles`:

https://github.com/cookiecutter/cookiecutter-django/blob/eca21f5b774e427c49989530766f9aa660c3d264/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/local.py#L45-L49

I haven't tried to re-generate a project to try to reproduce. What options have you used?

PS: we have an issue template which asks all these questions, would have been nice to follow it

**Comment by browniebroke** [comment] 2023-07-27 13:54
I cannot reproduce. When I run `python manage.py runserver --help` I can see the following output:

```
usage: manage.py runserver [-h] [--ipv6] [--nothreading] [--noreload] [--nostatic] [--insecure] [--version] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--no-color] [--force-color] [--skip-checks] [addrport]

Starts a lightweight web server for development and also serves static files. (Wrapped by 'whitenoise.runserver_nostatic' to always enable '--nostatic')
...
```

The part `(Wrapped by 'whitenoise.runserver_nostatic' to always enable '--nostatic')` indicates that [the whitenoise command](https://github.com/evansd/whitenoise/blob/514627c3bbd22beb5671260728fb577152ee071b/src/whitenoise/runserver_nostatic/management/commands/runserver.py#L50-L53) is used. 

I'm closing this as I cannot reproduce. Please provide more details to reproduce the problem on a fresh project generated from this template: options used and steps demonstrating the issue, with expected vs actual behaviour.

**Closed by browniebroke** 2023-07-27 13:54 UTC
Labels: bug
