### ISSUE TITLE
Build failed for node service on Docker + mac with M1 chip

### ISSUE THREAD

**Issue by EVENFATE** [cookiecutter/cookiecutter-django#3202] opened 2021-05-27 00:04 UTC
```
[+] Building 59.1s (9/9) FINISHED                                                                                                                         
 => [internal] load build definition from Dockerfile                                                                                                 0.0s
 => => transferring dockerfile: 191B                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                    0.0s
 => => transferring context: 34B                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/node:10-stretch-slim                                                                              2.7s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                          0.0s
 => [1/4] FROM docker.io/library/node:10-stretch-slim@sha256:88932859e3d022d79161b99628c4c2c50e836437455e2d1b1a008d98367b10d6                        0.0s
 => [internal] load build context                                                                                                                    0.1s
 => => transferring context: 34B                                                                                                                     0.0s
 => CACHED [2/4] WORKDIR /app                                                                                                                        0.0s
 => CACHED [3/4] COPY ./package.json /app                                                                                                            0.0s
 => ERROR [4/4] RUN npm install && npm cache clean --force                                                                                          56.3s
------                                                                                                                                                    
 > [4/4] RUN npm install && npm cache clean --force:                                                                                                      
#7 9.972 npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.                        
#7 13.51 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                              
#7 20.89 npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)                                                   
#7 21.45 npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
#7 26.42 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#7 41.85 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
#7 42.25 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
#7 53.48 
#7 53.48 > node-sass@4.14.1 install /app/node_modules/node-sass
#7 53.48 > node scripts/install.js
#7 53.48 
#7 53.78 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-64_binding.node
#7 55.58 Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-64_binding.node": 
#7 55.58 
#7 55.58 HTTP error 404 Not Found
#7 55.58 
#7 55.58 Hint: If github.com is not accessible in your location
#7 55.58       try setting a proxy via HTTP_PROXY, e.g. 
#7 55.58 
#7 55.58       export HTTP_PROXY=http://example.com:1234
#7 55.58 
#7 55.58 or configure npm proxy via
#7 55.58 
#7 55.58       npm config set proxy http://example.com:8080
#7 55.68 
#7 55.68 > node-sass@4.14.1 postinstall /app/node_modules/node-sass
#7 55.68 > node scripts/build.js
#7 55.68 
#7 55.75 Building: /usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#7 55.79 gyp info it worked if it ends with ok
#7 55.80 gyp verb cli [ '/usr/local/bin/node',
#7 55.80 gyp verb cli   '/app/node_modules/node-gyp/bin/node-gyp.js',
#7 55.80 gyp verb cli   'rebuild',
#7 55.80 gyp verb cli   '--verbose',
#7 55.80 gyp verb cli   '--libsass_ext=',
#7 55.80 gyp verb cli   '--libsass_cflags=',
#7 55.80 gyp verb cli   '--libsass_ldflags=',
#7 55.80 gyp verb cli   '--libsass_library=' ]
#7 55.80 gyp info using node-gyp@3.8.0
#7 55.80 gyp info using node@10.24.1 | linux | arm64
#7 55.80 gyp verb command rebuild []
#7 55.80 gyp verb command clean []
#7 55.80 gyp verb clean removing "build" directory
#7 55.80 gyp verb command configure []
#7 55.81 gyp verb check python checking for Python executable "python2" in the PATH
#7 55.81 gyp verb `which` failed Error: not found: python2
#7 55.81 gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#7 55.81 gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#7 55.81 gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#7 55.81 gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#7 55.81 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#7 55.81 gyp verb `which` failed  python2 { Error: not found: python2
#7 55.81 gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#7 55.81 gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#7 55.81 gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#7 55.81 gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#7 55.81 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#7 55.81 gyp verb `which` failed   stack:
#7 55.81 gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/app/node_modules/which/which.js:13:12)\n    at F (/app/node_modules/which/which.js:68:19)\n    at E (/app/node_modules/which/which.js:80:29)\n    at /app/node_modules/which/which.js:89:16\n    at /app/node_modules/isexe/index.js:42:5\n    at /app/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
#7 55.81 gyp verb `which` failed   code: 'ENOENT' }
#7 55.81 gyp verb check python checking for Python executable "python" in the PATH
#7 55.81 gyp verb `which` failed Error: not found: python
#7 55.81 gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#7 55.81 gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#7 55.81 gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#7 55.81 gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#7 55.81 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#7 55.81 gyp verb `which` failed  python { Error: not found: python
#7 55.81 gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#7 55.81 gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#7 55.81 gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#7 55.81 gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#7 55.81 gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#7 55.81 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#7 55.81 gyp verb `which` failed   stack:
#7 55.81 gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/app/node_modules/which/which.js:13:12)\n    at F (/app/node_modules/which/which.js:68:19)\n    at E (/app/node_modules/which/which.js:80:29)\n    at /app/node_modules/which/which.js:89:16\n    at /app/node_modules/isexe/index.js:42:5\n    at /app/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
#7 55.81 gyp verb `which` failed   code: 'ENOENT' }
#7 55.81 gyp ERR! configure error 
#7 55.81 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#7 55.81 gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
#7 55.81 gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
#7 55.81 gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
#7 55.81 gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
#7 55.81 gyp ERR! stack     at /app/node_modules/which/which.js:89:16
#7 55.81 gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
#7 55.81 gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
#7 55.81 gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
#7 55.81 gyp ERR! System Linux 5.10.25-linuxkit
#7 55.81 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#7 55.81 gyp ERR! cwd /app/node_modules/node-sass
#7 55.81 gyp ERR! node -v v10.24.1
#7 55.81 gyp ERR! node-gyp -v v3.8.0
#7 55.81 gyp ERR! not ok 
#7 55.81 Build failed with error code: 1
#7 56.05 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
#7 56.05 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#7 56.05 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/glob-watcher/node_modules/chokidar/node_modules/fsevents):
#7 56.05 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#7 56.05 npm WARN ots@0.1.0 No description
#7 56.05 npm WARN ots@0.1.0 No repository field.
#7 56.05 npm WARN ots@0.1.0 No license field.
#7 56.05 
#7 56.08 npm ERR! code ELIFECYCLE
#7 56.08 npm ERR! errno 1
#7 56.08 npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
#7 56.08 npm ERR! Exit status 1
#7 56.08 npm ERR! 
#7 56.08 npm ERR! Failed at the node-sass@4.14.1 postinstall script.
#7 56.08 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#7 56.09 
#7 56.09 npm ERR! A complete log of this run can be found in:
#7 56.09 npm ERR!     /root/.npm/_logs/2021-05-26T22_05_48_899Z-debug.log
------
executor failed running [/bin/sh -c npm install && npm cache clean --force]: exit code: 1
ERROR: Service 'node' failed to build : Build failed
```

 Apple M1 chips build,How to fix it

**Comment by luzfcb** [comment] 2021-06-08 13:47
@EVENFATE what are the exact options you chose when generating the project?

**Comment by RobRoseKnows** [comment] 2021-06-18 19:26
I have the same issue. I used the following options:
```
timezone [UTC]: EST
windows [n]: n
use_pycharm [n]:
use_docker [n]: y
Select postgresql_version:
1 - 12.3
2 - 11.8
3 - 10.8
4 - 9.6
5 - 9.5
Choose from 1, 2, 3, 4, 5 [1]: 1
Select js_task_runner:
1 - None
2 - Gulp
Choose from 1, 2 [1]: 2
Select cloud_provider:
1 - AWS
2 - GCP
3 - None
Choose from 1, 2, 3 [1]: 1
Select mail_service:
1 - Mailgun
2 - Amazon SES
3 - Mailjet
4 - Mandrill
5 - Postmark
6 - Sendgrid
7 - SendinBlue
8 - SparkPost
9 - Other SMTP
Choose from 1, 2, 3, 4, 5, 6, 7, 8, 9 [1]: 6
use_async [n]: y
use_drf [n]: y
custom_bootstrap_compilation [n]: n
use_compressor [n]: y
use_celery [n]: y
use_mailhog [n]: y
use_sentry [n]: n
use_whitenoise [n]: y
use_heroku [n]: y
Select ci_tool:
1 - None
2 - Travis
3 - Gitlab
4 - Github
Choose from 1, 2, 3, 4 [1]: 4
keep_local_envs_in_vcs [y]: y
debug [n]: n
```

This is a pretty fresh M1 Mac Mini.

**Comment by RobRoseKnows** [comment] 2021-06-18 19:45
I think https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#node-gyp-alpine might be relevant to this error.

**Comment by RobRoseKnows** [comment] 2021-06-18 20:00
I was able to fix this temporarily by using `FROM node:10` instead of `FROM node:10-stretch-slim`. It's a lot slower to build though. I would recommend a better solution, though I'm not familiar enough with docker to really say what that is.

**Comment by crukundo** [comment] 2021-07-07 08:45
I am still having this issue too. And the ARG fix from @luzfcb in #3188 didn't help (I'm running the latest build).

**Comment by luzfcb** [comment] 2021-07-07 09:34
@crukundo can you please provide more informations? [Follow this template.](https://github.com/pydanny/cookiecutter-django/blob/master/.github/ISSUE_TEMPLATE/bug.md#additional-details)
If you using OSX, can you also check in the Docker Desktop Experimental Settings of Docker Desktop if the Compose V2 is enabled or not?

**Comment by browniebroke** [comment] 2021-11-11 23:22
I was hoping to be able to reproduce in #3394 but it's all working fine. However, we're getting a similar error in the #3336.

**Comment by browniebroke** [comment] 2021-11-13 14:40
@EVENFATE @RobRoseKnows @crukundo could give #3400 a try and check whether it fixes your problem? The error seems to complain about `node-sass` and I think we're no longer using it in that PR. You can try with:

```sh
cookiecutter https://github.com/browniebroke/cookiecutter-django --checkout update/node-deps
```

**Comment by browniebroke** [comment] 2021-11-16 20:35
I've now merged the #3400 as it was a good upgrade to do and it seemed to be working. You can now try it out from the default branch on this repo:

```
cookiecutter https://github.com/cookiecutter/cookiecutter-django
```

If someone could comment here to let us know if the problem is fixed that would be nice.

**Closed** 2021-12-02 19:25 UTC
Labels: docker, bug, macOS, m1, waiting

**Comment by xjlin0** [comment] 2022-01-08 01:51
Hi team, I used to setup Django cookie cutter with docker-machine + Virtualbox on Intel Mac. Since docker-machine deprecated and Virtualbox won't arrive M1 soon, are there any documents show how to start development of  Django cookie cutter with docker on M1 Mac? thanks!

**Comment by Andrew-Chen-Wang** [comment] 2022-01-08 03:29
docker machine seems to have been deprecated: https://docs.docker.com/machine/

Simply use docker-compose on Apple Silicon
