### ISSUE TITLE
Migrate to Django 4.2 storage object syntax

### ISSUE THREAD

**Issue by jkaeske** [cookiecutter/cookiecutter-django#4799] opened 2024-01-22 15:07 UTC
## Description

Django 4.2 changed the way storage objects can be defined. A subclassing in the `storages.py` is not necessary anymore and storages can be defined like so in the settings file instead:

```
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
          ...your_options_here
        },
    },
}
```

Django-storages "strongly encourages" the switch to this way of defining the storage objects, as written in the [documentation](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html).

## Rationale

This would be in line with django-storages documentation, simplify the code base by deleting the storages.py file, and would give an easy possibility to add more storage objects.

## Solution

If it needs to be changed, I can do it.

**Comment by browniebroke** [comment] 2024-01-22 15:39
Duplicate of #4443

**Closed by browniebroke** 2024-01-22 15:39 UTC
Labels: enhancement
