### ISSUE TITLE
Docs update: Can't exec into container to run management commands

### ISSUE THREAD

**Issue by camrail** [cookiecutter/cookiecutter-django#3224] opened 2021-06-14 11:27 UTC
Hi All,

Firstly thanks for this repo, it's amazing and as you well know saves countless hours (first time using it).

Usually when I setup my django with docker projects I do it in such a way that I exec into the container
`docker exec -it django bash` and then run management commands `python manage.py migrate`

This wasn't working (I was getting a DATABASE_URL missing error), and after some running around thinking I had somehow configured something wrong I came across this post https://github.com/pydanny/cookiecutter-django/issues/2848 which made me realise that I needed to run them this way without exec'ing in:
`docker-compose -f local.yml run --rm django python manage.py migrate`

I gather it's because of the way the environment variables are injected.  I'm not sure if this is obvious to most people but it wasn't to me and I was just wondering if it would be helpful to call out in the docs that you cannot exec into the container and run manage.py that way?  I know it calls out "this is how you execute management commands" but I thought those two methods were interchangeable.  Again could just be me not knowing enough about docker.

Thanks

**Comment by Andrew-Chen-Wang** [comment] 2021-07-02 06:34
hmm `docker exec` requires a container id no? And if not, then you'd need to add `--name` before `django` (I think) assuming that's the container name that you see in `docker container ls -a`. In other words, I *think* you may just have a syntax error

**Comment by temp5374** [comment] 2021-07-05 07:15
Hi Andrew `django` is the container name and you don't need `--name` in my experience.

If there was a syntax error in the exec and it was failing completely then I wouldn't have been seeing the DATABASE_URL Django stacktrace.

Based on your response though, are you expecting that environment variables are injected in a way that this should work?  and  that it is different to #2848?

Thanks!

**Comment by Andrew-Chen-Wang** [comment] 2021-07-05 15:50
Ah you know what I think you're right.

> Based on your response though, are you expecting that environment variables are injected in a way that this should work?

Yea, I assumed that because you weren't injecting environment variables via compose (since you were using `exec` directly), the .env file would have been parsed by Django-environ. I guess it wasn't.

Seems like #2848 does answer this issue though.

Regarding actually adding this to the docs, I think it's already in there for docker: https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html#execute-management-commands

Though it specifically mentions for management commands, I thought it was well known for compose configuration to use `docker-compose run` (though I learned docker from this repo, so that might be my bias). Idk thoughts?

**Comment by browniebroke** [comment] 2021-12-07 20:28
> hmm `docker exec` requires a container id no? And if not, then you'd need to add `--name` before `django` (I think) assuming that's the container name that you see in `docker container ls -a`. In other words, I _think_ you may just have a syntax error

You can provide the service name instead of container ID with `docker-compose exec`. I managed to reproduce with the following steps:

```
docker-compose -f local.yml build
docker-compose -f local.yml up -d django
docker-compose -f local.yml exec django python manage.py show_urls
```

Ideally both `run` and `exec` should work, but until it's the case, it would be clearer if it was documented.

> Regarding actually adding this to the docs, I think it's already in there for docker: [cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html#execute-management-commands](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html#execute-management-commands)

We could make it even more explicit by adding a sentence that `exec` isn't working. Also a section in troubleshooting would be worthwhile. WDYT? I'd happily review a PR with such changes

**Comment by Sophyia7** [comment] 2022-10-01 11:44
Hi, is this issue still open? If yes, can it be assigned to me?

**Comment by simevo** [comment] 2023-02-06 17:22
BTW I noticed that you can exec into django container if you prefix your command with `/entrypoint` as in:
```sh
docker-compose exec django /entrypoint python3 manage.py createsuperuser
```
on my system the `exec` commands run in ~3 s instead on ~5 s with `run --rm`

**Comment by infraredCoding** [comment] 2023-07-17 11:57
@browniebroke hey! I was wondering if this issue is still open. I'd love to add the changes in the docs

**Comment by browniebroke** [comment] 2023-07-24 11:42
Forgot to reply, but sure, please go ahead @infraredCoding

**Closed** 2023-07-27 13:42 UTC
Labels: docs, docker, good first issue
